name: List Commits in PR  
on:  
  push:
    branches: ['main']
  pull_request:  
    types: [opened, synchronize, reopened]  
  
jobs:  
  list-commits:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  
        with:  
          fetch-depth: 0 # 设置为 0 以获取完整的提交历史  
      - name: 测试
        run: |  
          echo "::set-output name=event::$(echo '${{ toJson(github.event) }}' | sed 's/"/\\"/g')"  
          # 注意：上述命令中的 `toJson` 并不是 GitHub Actions 的内置函数，这里仅用于示例  
          # GitHub Actions 实际上已经提供了 `github.event` 作为 JSON 对象，但我们不能直接打印其格式化的字符串  
          # 因此，上面的命令不会正常工作，只是一个概念上的例子
      # - name: List commits in PR  
      #   run: |  
      #     # 输出 PR 的标题和描述  
      #     ${{ github.event.pull_request.head }}  
      #     # 输出 base 分支的名称和 SHA 值  
      #     ${{ github.event.pull_request.base }}  
      #     # 使用 GitHub 提供的环境变量来获取 SHA 值  
      #     start_sha=${{ github.event.pull_request.base.sha }}  
      #     end_sha=${{ github.event.pull_request.head.sha }}  
  
      #     # 运行 git rev-list 命令  
      #     git rev-list "$start_sha..$end_sha"  
  
      # 如果你还想进一步处理这个列表（比如输出数量或格式化），可以在这里添加额外的步骤