name: List Commits in PR  
on:  
  push:
    branches: ['main']
  pull_request:  
    types: [opened, synchronize, reopened]  
  
jobs:  
  list-commits:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  
        with:  
          fetch-depth: 0 # 设置为 0 以获取完整的提交历史  
      - name: Get the first (oldest) commit hash
        run: |
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "First commit hash: $FIRST_COMMIT"

      - name: Get the last (most recent) commit hash
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          echo "Last commit hash: $LAST_COMMIT"
      - name: List commits in PR  
        run: |
          # LAST_COMMIT=$(git rev-parse HEAD)
          echo "Last commit hash: $LAST_COMMIT"
          git rev-list "$FIRST_COMMIT..$LAST_COMMIT"  
  
      # 如果你还想进一步处理这个列表（比如输出数量或格式化），可以在这里添加额外的步骤